// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaAPI.Repositories.Contexts;

#nullable disable

namespace NovaAPI.Repositories.Migrations.NovaAPIDb
{
    [DbContext(typeof(NovaAPIDbContext))]
    [Migration("20250312182222_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("NovaAPI.Entities.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("ADDRESS")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("DOCUMENT")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("EMAIL")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasColumnName("NAME")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("PHONE")
                        .UseCollation("Latin1_General_CI_AI");

                    b.HasKey("CustomerId")
                        .HasName("PK_TB_CUSTOMER");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IDX_TB_CUSTOMER_01");

                    b.ToTable("TB_CUSTOMER", (string)null);
                });

            modelBuilder.Entity("NovaAPI.Entities.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ORDER_ID");

                    b.Property<int>("CustomerId")
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("DATE");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasColumnName("NUMBER")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("STATUS")
                        .UseCollation("Latin1_General_CI_AI");

                    b.HasKey("OrderId")
                        .HasName("PK_TB_ORDER");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IDX_TB_ORDER_01");

                    b.ToTable("TB_ORDER", (string)null);
                });

            modelBuilder.Entity("NovaAPI.Entities.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ORDER_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRODUCT_ID");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("PK_TB_ORDERPRODUCT");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IDX_TB_ORDERPRODUCT_02");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IDX_TB_ORDERPRODUCT_01");

                    b.ToTable("TB_ORDERPRODUCT", (string)null);
                });

            modelBuilder.Entity("NovaAPI.Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar")
                        .HasColumnName("DESCRIPTION")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("NAME")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(2)
                        .HasColumnType("Money")
                        .HasColumnName("PRICE");

                    b.HasKey("ProductId")
                        .HasName("PK_TB_PRODUCT");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IDX_TB_PRODUCT_01");

                    b.ToTable("TB_PRODUCT", (string)null);
                });

            modelBuilder.Entity("NovaAPI.Entities.Models.Order", b =>
                {
                    b.HasOne("NovaAPI.Entities.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TB_ORDER_01");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NovaAPI.Entities.Models.OrderProduct", b =>
                {
                    b.HasOne("NovaAPI.Entities.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovaAPI.Entities.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NovaAPI.Entities.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("NovaAPI.Entities.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("NovaAPI.Entities.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
