// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaAPI.Repositories.Contexts;

#nullable disable

namespace NovaAPI.Repositories.Migrations.NovaAPIDb
{
    [DbContext(typeof(NovaAPIDbContext))]
    [Migration("20250311154437_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("NovaAPI.Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("NAME")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<decimal>("Price")
                        .HasPrecision(2)
                        .HasColumnType("Money")
                        .HasColumnName("PRICE");

                    b.HasKey("ProductId")
                        .HasName("PK_TB_PRODUCT");

                    b.ToTable("Products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
